nilai = set({3,6,9,2,5,7})
nilai2 = {1,4,8,10}
nilai.update(nilai2)
print("Nilai setelah update :" , nilai)
nilai.discard(1)
nilai.discard(3)
nilai.discard(5)
nilai.discard(7)
nilai.discard(8)
nilai.discard(10)
nilai.discard(4)
print("Nilai setelah dihapus :" , nilai)